; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
default_envs = primary


; ============================================================================
; Common configuration for both Teensy 4.1 boards
; ============================================================================

[env]
platform = teensy
board = teensy41
framework = arduino

extra_scripts =
    pre:scripts/git_version.py

lib_deps =
    adafruit/Adafruit MAX31865 library
    greiman/SdFat


; ============================================================================
; Primary Teensy
; ============================================================================

[env:primary]

build_flags =
    -D FLIGHT_PRIMARY=1
    -D FLIGHT_SECONDARY=0


; ============================================================================
; Secondary Teensy
; ============================================================================

[env:secondary]

build_flags =
    -D FLIGHT_PRIMARY=0
    -D FLIGHT_SECONDARY=1